---
title: "REDCap Project Deletion history"
author: "Philip Chase"
date: "7/1/2018"
output:
  html_document:
    highlight: kate
    theme: cosmo
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load_libraries, echo=FALSE, message=FALSE, warning=FALSE, comment=NA}

if (!require("pacman")) install.packages("pacman")
pacman::p_load(
  dplyr,
  ggplot2,
  lubridate,
  tidyr
  )

```

```{r get_inputs, include=FALSE}
# Inputs and outputs are read from a subdirectory of the ~/Downloads folder for convenience.
mainDir <- c("~/Downloads/")
subDir <- c("project_lifecycle")
download_directory <- file.path(mainDir, subDir)
dir.create(file.path(mainDir, subDir), showWarnings = FALSE)
require("knitr")
opts_knit$set(root.dir = download_directory)

col_classes <- c("integer", "integer", "character",
                 "character", "character", "factor",
                 "factor", "factor", "character",
                 "integer", "factor", "character",
                 "factor", "character", "character",
                 "character", "character")
del_events <- read.csv(file.path(download_directory, "project_deletion_history.csv"), header=TRUE, sep = ",", quote = '"', stringsAsFactors=FALSE, strip.white=TRUE, na.strings = "NULL", colClasses = col_classes)

redcap_staff <- read.csv(file.path(download_directory,"redcap_staff.csv"), stringsAsFactors = FALSE)
```

```{r mutate_inputs, include=FALSE}
del_events$event_date <- ymd(del_events$event_date)

```

# REDCap project deletion history on the CTSI REDCap instance

This reports summarizes REDCap project deletion activity on the CTSI REDCap instance. The hope is that the metrics and visualizatons presented here can show how policy changes on this REDCap instance influence the use of the system.

```{r project_deleters, echo=FALSE}
# Determine the last user to request deletion
deleter_requested <- del_events %>%
  filter(description %in% c('Send request to delete project')) %>%
  group_by(project_id) %>%
  arrange(ts) %>%
  slice(1) %>%
  select(ts, project_id, user, event_date)

# Determine the last user to execute the deletion when there was no requester
deleter_actual<- del_events %>%
  filter(description %in% c('Delete project')) %>%
  group_by(project_id) %>%
  arrange(ts) %>%
  slice(1) %>%
  select(ts, project_id, user, event_date) %>%
  filter(!project_id %in% deleter_requested$project_id)

# Make one data set with the project deleter
project_deleters <- bind_rows(deleter_requested, deleter_actual) %>%
  rename(deleter = user) %>%
  filter(!deleter %in% redcap_staff$user)

```

```{r deletion_by_time, include=FALSE}
# Select only permanent deletions group by event_date and plot result
deletions_by_month <- project_deleters %>%
  select(project_id, event_date) %>%
  group_by(month = floor_date(event_date, "month")) %>%
  summarise(deletions = n())
```

```{r plot_deletion_by_time, echo=FALSE}
# Plot the size of deletion activity over time
ggplot(data=deletions_by_month, aes(x=month, y=deletions))  +
  geom_point() +
  ylab("Count") +
  xlab("Month") +
  scale_x_date() +
  ggtitle("Project deletions by month")
```

```{r deletion_by_time_detail, include=FALSE}
# Show the detail of deletion activity since the policy announcement
policy_announcement_date <- ymd("2018-05-15")
deletions_by_week <- project_deleters %>%
  select(project_id, event_date) %>%
  filter(event_date >= ymd("2018-05-01")) %>%
  group_by(week = floor_date(event_date, "week")) %>%
  summarise(deletions = n())
```

```{r plot_deletion_by_time_detail, echo=FALSE}
# Plot the size of deletion activity over time
ggplot(data=deletions_by_week, aes(x=week, y=deletions))  +
  geom_point() +
  ylab("Count") +
  xlab("Week") +
  scale_x_date() +
  geom_vline(xintercept = policy_announcement_date) +
  annotate("text", label = "Policy Announcement", x=policy_announcement_date, y = 0.9 * max(deletions_by_week$deletions), angle = 90) +
  ggtitle("Project deletions by week since the May 15th policy announcement")
```

These people are our top deleters since the policy announcement:

```{r top_deleters, echo=FALSE}
top_deleters <- project_deleters %>%
  filter(!deleter %in% redcap_staff$user) %>%
  filter(event_date >= policy_announcement_date) %>%
  group_by(deleter) %>%
  summarise(count=n()) %>%
  arrange(desc(count)) %>%
  filter(count > 5)

kable(top_deleters)

```
